#!/usr/bin/perl -w

use strict;

sub deb_list {
    my $debfile = shift;

    if (open(PIPE, "dpkg-deb -c $debfile |")) {
        my ($perms, $uid, $gid, $size, $date, $path);
        while (<PIPE>) {
            if (m!^([dl\-]([r\-][w\-][x\-]){3}) +(.+?)/(.+?) +(\d+) +([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}) \./(.+?)/{0,1}\n$!) {
                $perms = $1;
                $uid = $3;
                $gid = $4;
                $size = $5;
                $date = $6;
                $path = $7;
                $uid = getpwnam($uid) if ($uid !~ /^\d+$/);
                $gid = getgrnam($gid) if ($gid !~ /^\d+$/);
                print("$perms $uid $gid $size $date $path\n");
            }
        }
        close(PIPE);
    }
}

if (defined($ARGV[1]) && ($ARGV[0] eq "list")) {
    my $debfile = $ARGV[1];
    &deb_list($debfile);
} else {
    exit(1);
}

exit(0);
