#!/usr/bin/perl -w

use strict;

use constant {
    false => 0,
    true  => 1
};

sub rar_list {
    my $rarfile = shift;

    if (open(PIPE, "unrar v -c- -y $rarfile |")) {
        my $parse = false;
        my ($size, $mday, $mon, $year, $hour, $min, $dir, $name);
        while (<PIPE>) {
            if (/^\-{10,}/) {
                if (!$parse) {
                    $parse = true;
                    next;
                } else {
                    last;
                }
            }
            if ($parse) {
                if (/^ +[I.][C.][A.]([D.])[S.][H.][R.] +(\d+) +\d+ +\d+% +([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}) +[A-F0-9]{8} +(.+)\n/) {
                    $dir = $1;
                    $size = $2;
                    $year = $3;
                    $mon = $4;
                    $mday = $5;
                    $hour = $6;
                    $min = $7;
                    $name = $8;
                    printf("%s 0 0 %s %04d-%02d-%02d %02d:%02d %s\n",
                        ($dir eq 'D') ? 'drwxr-xr-x' : '-rw-r--r--',
                        $size,
                        $year, $mon, $mday, $hour, $min,
                        $name);
                }
            }
        }
        close(PIPE);
    }
}

if (defined($ARGV[1]) && ($ARGV[0] eq "list")) {
    my $rarfile = $ARGV[1];
    &rar_list($rarfile);
} else {
    exit(1);
}

exit(0);
